---

:project:
  :use_exceptions: TRUE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build

:paths:
  :test:
    - test/*
  :source:
    - src/*
  :include:
    - src/*
#  :test_toolchain_include:
#    - tools/mingw/include

:defines:
  :common: &common_defines
  :test:
    - TEST
    - *common_defines
  :release:
    *common_defines

:module_generator:
  :project_root: ./
  :source_root: src/
  :test_root: test/
  :header_includes:
    - Types.h
  :test_includes:
    - Types.h
    - UnityHelper.h

:cmock:
  :mock_prefix: Mock
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :includes:
    - Types.h
  :plugins:
    - :ignore
  :treat_as:
    U8:   UINT
    U16:  UINT
    U32:  UINT
    S8:   HEX8
    U8*:  HEX32
    U16*: HEX32
    C8*:  STRING

:plugins:
  :base_path: tools/ceedling/plugins
  :auxiliary_load_path: tools/ceedling/plugins/support
  :enabled:
    - stdout_ide_tests_report
    - module_generator

...
