---

:project:
  :use_exceptions: TRUE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
#  :release_build: TRUE
  :test_file_prefix: test_

#:release_build:
#  :output: TempSensor.out
#  :use_assembly: FALSE

:environment:

#:extension:
#  :executable: .out

:paths:
  :test:
    - test/*
    - test/support/*
  :source:
    - src/*
  :support:
    - test/support

:defines:
  :common: &common_defines
  :test:
    - TEST
    - *common_defines
  :release:
    *common_defines

:cmock:
  :mock_prefix: Mock
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :includes:
    - Types.h
  :plugins:
    - :ignore
  :treat_as:
    U8:   UINT
    U16:  UINT
    U32:  UINT
    S8:   HEX8
    U8*:  HEX32
    U16*: HEX32
    C8*:  STRING

:module_generator:
  :project_root: ./
  :source_root: src/
  :test_root: test/
  :header_includes:
    - Types.h
  :test_includes:
    - Types.h
    - UnityHelper.h

:plugins:
  :load_paths:
    - vendor/ceedling/plugins
  :enabled:
    - stdout_pretty_tests_report

...
